### ISSUE TITLE
Add support for Variables API

### ISSUE THREAD

**Issue by ViViDboarder** [jrxFive/python-nomad#139]
As of Nomad 1.4, there is now the ability to use Nomad to store variables that can be accessed by jobs.

API documentation: https://developer.hashicorp.com/nomad/api-docs/variables

This is something that I'd be interested in adding at some point myself so I can build it into an Ansible module if nobody gets around to it.

**Comment by nikita-b** [comment]
I'm working on it right now. I hope it'll be finished this week and will be available as a 1.5.0 version.

**Comment by nikita-b** [comment]
Support was added in https://github.com/jrxFive/python-nomad/pull/141
