### ISSUE TITLE
support docker volume

### ISSUE THREAD

**Issue by elfore** [jrxFive/python-nomad#25]
when  should python-nomad support nomad 0.5.*, and add docker volume support?

**Comment by jrxFive** [comment]
Hey @elfore, have not been able to getting around to fixing the CI integration tests to verify support for nomad 0.5.x, I do not believe there were any breaking changes to the actual nomad HTTP API. As for docker volume support python-nomad should not be enforcing anything that you specify in your driver configuration for your tasks, as long as the actual nomad server supports that configuration python-nomad should just be sending the correct HTTP calls. If that's not what you are seeing could you add the calls that were attempted.

I'll try to fix the CI tests ASAP to verify.

**Comment by jrxFive** [comment]
Fixed testing for 0.5.x (#24) it was an issue with using a static example.nomad that was from an older version of nomad and didn't allow submission. Have since just generated the nomad/json file per version. Please let me know if you are having an issue with docker volumes per python-nomad

**Comment by jrxFive** [comment]
Closing for now will reopen if docker volume is not working through python-nomad.
