### ISSUE TITLE
Add 0.7.0 support

### ISSUE THREAD

**Issue by jonathanrcross** [jrxFive/python-nomad#40]
Additions to the API:

- namespaces
- acl policies
- acl tokens
- sentinel policies
- search

Will have to mock enterprise calls (namespaces, sentinel)

**Comment by i4s-pserrano** [comment]
I have made several changes to cover:

- namespaces
- ACL token

I changed the way  to configure the api using uri in behalf of ip
https://github.com/i4s-pserrano/python-nomad

regards

**Comment by i4s-pserrano** [comment]
I have made a fork to avoid some of those features 

https://github.com/i4s-pserrano/python-nomad/tree/add_namespace_and_token

**Comment by i4s-pserrano** [comment]
this fork was merged. #41
