### ISSUE TITLE
Add support for API v0.7

### ISSUE THREAD

**Issue by alinoe-abrassart** [jrxFive/python-nomad#53]
It seems that the endpoint for creating a job has changed in the version 0.7.4 of the HTTP API: https://www.nomadproject.io/api/jobs.html#create-job

**Comment by jrxFive** [comment]
Oh wow I'll look into that! Tests should have failed so guess there is an issue with the tests itself.  Thanks for pointing that out @alinoe-abrassart

**Comment by alinoe-abrassart** [comment]
The endpoint seems to be implemented, it is just missing in the doc.

**Comment by jrxFive** [comment]
added register job in docs with #54
