### ISSUE TITLE
plan_job does not use the diff flag correctly

### ISSUE THREAD

**Issue by jeteon** [jrxFive/python-nomad#60]
According to the [docs](https://www.nomadproject.io/api/jobs.html#create-job-plan) the Nomad API expects a `Diff` parameter to be optionally supplied in the payload of the request like so:

> <pre>{
>   "Job": "...",
>   "Diff": true,
>   "PolicyOverride": false
> }</pre>

However the code adds this as a parameter on the URL instead:
https://github.com/jrxFive/python-nomad/blob/1e929b98d3c9ca8d76038eca7a7ba52d06a66afe/nomad/api/job.py#L192-L206

This results in you not being able to actually request a diff on a plan by calling `nomad.job_plan(id, job, diff=True)` since it is not put into the body and thus ignored by the Nomad server.

**Comment by jrxFive** [comment]
Merged in #61
