### ISSUE TITLE
`plan_job` breaking change

### ISSUE THREAD

**Issue by mentalisttraceur** [jrxFive/python-nomad#63]
[Pull request 61](https://github.com/jrxFive/python-nomad/pull/61) was a breaking change. Previously, this worked to get the diff:

    my_nomad.job.plan_job(job['ID'], {'Job': job, 'Diff': True})

This is conceptually congruent with the current interface, which requires wrapping the actual job definition dict in the `{'Job': ... }` dict which normally holds the `Diff` field as well, as one must when calling the API directly.

With the merged change, `json_dict["Diff"] = diff` will force the `Diff` to the default value of `False` when called as above.

An easy fix would be to change that line to `json_dict.setdefault('Diff', diff)`.

**Comment by jrxFive** [comment]
Hey mentalisttraceur, thanks fore reporting this, something I should have thought of. Should be fixed in #65.
