### ISSUE TITLE
`my_nomad.jobs.parse` not documented.

### ISSUE THREAD

**Issue by mentalisttraceur** [jrxFive/python-nomad#64]
I couldn't find any documentation of the `parse` function added in pull request #55 .

I think it's a pretty critical function for actually using Nomad programmatically, since that's the form of job definition that is extensively documented and expected/written/read by users, so it would be good to have an entry in the docs for it.

**Comment by maxmcd** [comment]
Surely this endpoint is a convenience? You could use an HCL parsing lib and use json directly with this SDK?

That being said, I appreciate this issue and found it looking to see if HCL parsing was built-in to the lib.

**Comment by jrxFive** [comment]
Added documentation on how to use this endpoint in 1.0.0
