### ISSUE TITLE
enforceIndex and jobModifyIndex

### ISSUE THREAD

**Issue by greut** [jrxFive/python-nomad#97]
I'd love to be able to send the jobModifyIndex to the `register_job` call.

c.f. https://www.nomadproject.io/api/jobs.html#create-job

**Comment by nikita-b** [comment]
These are slightly late comments but people can still find this issue through Google...
You can do it even now:
```
    nomad_api.jobs.register_job(job={"Job": job_json, "EnforceIndex": True, "JobModifyIndex"=index_number})
```
I'll close the issue but if you have questions feel free to ask.
