### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by erhlee-bird** [jrxFive/python-nomad#98]
Hey @jrxFive, the repo description says that you are looking for maintainers.

I would love to volunteer time to help out.
Is there anything you're looking for in particular?

**Comment by jrxFive** [comment]
Hey @erhlee-bird, I haven't really had the time to spend to keep this library in parity with this nomad API. There are quite a few endpoint it doesn't support yet. Such as `search` and any changes (querystrings, payloads) within the other endpoints and to which version those changes are reflected in.

Beforehand I was using nomad pretty regularly at work and would be able to contribute when issues would arise in my spare time. 

So hoping to find others that can help push out new releases while staying as backwards compatible as possible.

**Comment by erhlee-bird** [comment]
In that case, I'd be very happy to assist and support those goals @jrxFive.

**Comment by renemoser-sbb** [comment]
Hi @jrxFive @erhlee-bird, I relay on this module and offer to help out maintaining it.

**Comment by resmo** [comment]
(sorry, wrong user...)

I would like to offer some time for maintaining it.

**Comment by erhlee-bird** [comment]
@jrxFive, would you have some availability to chat with @resmo and I about helping maintain this project?

**Comment by jonathanrcross** [comment]
Hi @erhlee-bird, @resmo, thanks for reminding be about this. I have sent you both invites to a gitter chatroom to chat further about this if that works for you. If you want use another tool im certainly open to that as well, can send me an direct email with details.
